# Generated by Django 2.2.12 on 2021-09-13 15:14

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_group', to='otree.Session')),
            ],
            options={
                'db_table': 'q_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'q_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('gender', otree.db.models.BooleanField(choices=[[0, 'Male'], [1, 'Female']], null=True, verbose_name='Ваш пол')),
                ('best_intensions', otree.db.models.PositiveIntegerField(choices=[[0, '0 - Totally disagree'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally agree'], [999, 'Hard to say']], null=True, verbose_name='I assume that people have only the best intentions')),
                ('smoke', otree.db.models.PositiveIntegerField(choices=[[0, 'Never'], [1, 'Occasionally'], [2, 'Frequently'], [999, 'Hard to say']], null=True, verbose_name='How frequently do you smoke?')),
                ('fast_drive', otree.db.models.PositiveIntegerField(choices=[[0, 'Never'], [1, 'Occasionally'], [2, 'Frequently'], [3, 'I do not drive'], [999, 'Hard to say']], null=True, verbose_name='How often do you drive faster with your car than allowed by the traffic regulations?')),
                ('income_diff', otree.db.models.PositiveIntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='Differences in income in Russia are too large')),
                ('reduce_income_diff', otree.db.models.PositiveIntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='It is the responsibility of the government to reduce the differences in income between people with high incomes and those with low incomes')),
                ('income', otree.db.models.PositiveIntegerField(choices=[[1, 'Not even enough money for food'], [2, 'Enough for food, but not enough to buy clothes and shoes'], [3, 'Enough for clothes and shoes, but not enough to buy small appliances'], [4, 'Enough money for small purchases, but buying expensive things (computer, washing machine, refrigerator) requires savings or credit'], [5, 'Have enough money to buy for the house, but to buy a car, dacha, apartment requires saving or taking a loan'], [6, 'Can afford any purchases without restrictions or credit'], [999, 'Hard to say']], null=True, verbose_name='Which statement best describes the financial situation in your family?')),
                ('fin_situation_change', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Did your family financial situation change over the last year? How would you answer the previous question a year ago?')),
                ('regional_diff', otree.db.models.PositiveIntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='Do you agree with the statement that the differences in the level of income between the regions of Russia are unjustifiably large?')),
                ('regional_income_changed', otree.db.models.PositiveIntegerField(choices=[[1, 'It became substantially smaller than a year ago'], [2, 'It became a bit smaller than a year ago'], [3, 'It did not change'], [4, 'It became a bit larger than a year ago'], [5, 'It became substantially large than a year ago'], [999, 'Hard to say']], null=True, verbose_name='In your opinion, did the the average monthly income of the residents of your region change over the last year?')),
                ('relative_income', otree.db.models.PositiveIntegerField(choices=[[1, 'lower than the average in your city'], [2, 'the same as the average in your city'], [3, 'higher than the average in your city'], [999, 'Hard to say']], null=True, verbose_name='Your average monthly income...')),
                ('Patience_10_1', otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name='How willing are you to give up something that is beneficial for you today in order to benefit more from that in the future?')),
                ('Patience_10_2', otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name=' How willing are you to punish someone who treats others unfairly, even if there may be costs for you?')),
                ('Patience_10_3', otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name='When someone does me a favor, I am willing to return it')),
                ('Patience_10_4', otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name='If I have been treated unfairly, I will retaliate at the first opportunity, even if it costs me a lot')),
                ('risk_general', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='')),
                ('risk_fin', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name="In financial matters'")),
                ('risk_sport', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='In leisure and sport')),
                ('risk_prof', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='In professional career')),
                ('risk_health', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='In health')),
                ('risk_strangers', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='With strangers')),
                ('risk_drive', otree.db.models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='While driving')),
                ('ready_help', otree.db.models.IntegerField(choices=[[0, '0 - Completely unwilling to spend money'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Very willing to spend money'], [999, 'Hard to say']], null=True, verbose_name='Willingness to spend money even at not return')),
                ('donated_money', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Have you donated money in the previous 12 months?')),
                ('count_on_relatives', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Do you have relatives or friends you can count on to help you whenever needed?')),
                ('help_stranger', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you help a stranger in the previous 12 months who needed help?')),
                ('self_employed', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Are you self-employed?')),
                ('own_business', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='For those who are not self-employed: Are you planning to start your own business?')),
                ('save_money', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you save any money in the previous 12 months?')),
                ('fin_help', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you send help (money or goods) to another individual in the previous 12 months?')),
                ('vore_official', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you voice your opinion to a public official in the previous 12 months?')),
                ('volunteer', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you voluntarily devote time to an organization in the previous 12 months?')),
                ('police_confidence', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='In the city or area where you live, do you have confidence in the local police force?')),
                ('safety', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Do you feel safe walking alone at night in the city or area where you live?')),
                ('stolen_money', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Has money or property been stolen from you or another household member within the last 12 months? ')),
                ('used_trust', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did someone take advantage of your trust in the last 6 months?')),
                ('reciprocated_trust', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you experience a positive response in the last 6 months when you trusted someone?')),
                ('disappointed_trust', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Have you disappointed someone in the last 6 months who has trusted you?')),
                ('donated_blood', otree.db.models.IntegerField(choices=[[0, 'No'], [1, 'Yes'], [999, 'Hard to say']], null=True, verbose_name='Did you donate blood during the last 6 months?')),
                ('big5_1', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who is reserved')),
                ('big5_2', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who is generally trusting')),
                ('big5_3', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who tends to be lazy')),
                ('big5_4', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who is relaxed, handles stress well')),
                ('big5_5', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who has few artistic interests')),
                ('big5_6', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who is outgoing, sociable')),
                ('big5_7', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who tends to find fault with others')),
                ('big5_8', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who does a thorough job')),
                ('big5_9', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who gets nervous easily')),
                ('big5_10', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who has an active imagination')),
                ('big5_11', otree.db.models.IntegerField(choices=[[1, 'Totally disagree'], [2, 'Somewhat disagree'], [3, 'Neither agree nor disagree'], [4, 'Somewhat agree'], [5, 'Absolutely agree'], [999, 'Hard to say']], null=True, verbose_name='I see myself as someone who is reserved')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='q.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q.Subsession')),
            ],
            options={
                'db_table': 'q_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q.Subsession'),
        ),
    ]
