# Generated by Django 2.2.12 on 2021-09-13 15:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='best_intensions',
        ),
        migrations.AddField(
            model_name='player',
            name='best_intentions',
            field=otree.db.models.PositiveIntegerField(choices=[[0, '0 - Totally disagree'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally agree'], [999, 'Hard to say']], null=True, verbose_name='I assume that people have only the best intentions'),
        ),
        migrations.AddField(
            model_name='player',
            name='regional_average_income',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='In your opinion, what is the average monthly income of the residents of your region? Please write your estimate (in rubles per month)'),
        ),
    ]
