# Generated by Django 2.2.12 on 2021-09-13 15:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0004_auto_20210913_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fin_situation_change',
            field=otree.db.models.PositiveIntegerField(blank=True, choices=[[1, 'Not even enough money for food'], [2, 'Enough for food, but not enough to buy clothes and shoes'], [3, 'Enough for clothes and shoes, but not enough to buy small appliances'], [4, 'Enough money for small purchases, but buying expensive things (computer, washing machine, refrigerator) requires savings or credit'], [5, 'Have enough money to buy for the house, but to buy a car, dacha, apartment requires saving or taking a loan'], [6, 'Can afford any purchases without restrictions or credit'], [999, 'Hard to say']], null=True, verbose_name='Did your family financial situation change over the last year - How would you answer the previous question a year ago?'),
        ),
    ]
