# Generated by Django 2.2.12 on 2021-09-13 15:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0005_auto_20210913_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Patience_10_1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Patience_10_2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Patience_10_3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Patience_10_4',
        ),
        migrations.AddField(
            model_name='player',
            name='patience_10_1',
            field=otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name='How willing are you to give up something that is beneficial for you today in order to benefit more from that in the future?'),
        ),
        migrations.AddField(
            model_name='player',
            name='patience_10_2',
            field=otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name=' How willing are you to punish someone who treats others unfairly, even if there may be costs for you?'),
        ),
        migrations.AddField(
            model_name='player',
            name='patience_10_3',
            field=otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name='When someone does me a favor, I am willing to return it'),
        ),
        migrations.AddField(
            model_name='player',
            name='patience_10_4',
            field=otree.db.models.IntegerField(choices=[[0, '0 - Totally unwilling to so'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10 - Totally willing to do so'], [999, 'Hard to say']], null=True, verbose_name='If I have been treated unfairly, I will retaliate at the first opportunity, even if it costs me a lot'),
        ),
    ]
