# Generated by Django 2.2.12 on 2021-09-13 15:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0007_auto_20210913_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.BooleanField(choices=[[0, 'Male'], [1, 'Female']], null=True, verbose_name='Indicate your gender'),
        ),
    ]
